{
  'name': 'KG Banquet',
  'author': 'CITIS Kompas Gramedia',
  'version': '0.1',
  'depends': [
    # 'nama_modul',
     'account',
     'withholding_tax',
     'eventtype',
     'kg_product'
  ],

  'data': [
    'data/banquet_sequence.xml',
    # 'security/access_rights.xml',
    # 'security/ir.model.access.csv',
    'views/templates.xml',
    'views/banquet.xml',
    'views/event_function.xml',
    'views/rate_type_view.xml',
    'views/room_type.xml',
    'views/reservation_source.xml',
    'views/instruction_view.xml',
    'views/market_segment_view.xml',
    'views/space_type.xml',
    # 'views/function_room_type.xml',
    # 'views/function_room.xml',
    # 'views/banquet_menu.xml',
    # 'views/event_menu.xml',
    # 'views/banquet_package.xml',
    # 'views/proposal_view.xml',
    # 'views/banquet_reservation.xml',
    # 'views/reservation_event.xml',
    # 'views/reservation_event_room_availability.xml',
    # 'views/reservation_resident.xml',
    # 'views/res_config.xml',
    # 'wizards/wizard_cancel_reason_view.xml',
    # 'views/reservation_advance_payment.xml',
    # 'data/cron_banquet_reservation.xml',
    # 'wizards/wizard_duplicate_reservation_resident.xml',
    # 'views/reservation_rate.xml',
    # 'wizards/wizard_duplicate_reservation.xml',
    'views/res_company.xml',
  ],
  'qweb': [
    'static/src/xml/custom_search_pms_guest_field.xml',
    # 'static/src/xml/custom_search_pms_room_rate_field.xml',
    # 'static/src/xml/nama_widget.xml',
    # 'static/src/xml/rename_button.xml',
  ],
  'sequence': 1,
  'auto_install': False,
  'installable': True,
  'application': True,
  'category': 'Banquet',
  'summary': 'Module Banquet',
  'license': 'OPL-1',
  'website': 'https://www.citiskg.com/',
  'description': '-'
}