# -*- coding: utf-8 -*-
{
    'name': "Kompas Gramedia Point Of Sale",
    'summary': """Point Of Sale Costumization for Kompas Gramedia.""",
    'description': """
        This module manages the followings:
            - Point Of Sale
    """,
    'author': "",
    'website': "",
    'category': 'Point of Sale',
    'version': '10.0.0.0.1',
    'depends': [
        'pos_restaurant',
        'kg_base',
        'kg_account',
        'hr_payroll',
        'hotel_id',
        'kg_product',
        'kg_report_base',
        'eventtype',
        'point_of_sale',
        'wk_coupons',
        'kg_banquet',
    ],
    'data': [
        'security/pos_access_rights.xml',
        'security/ir.model.access.csv',
        'views/kg_pos_config.xml',
        'views/kg_pos_order.xml',
        # 'views/kg_pos_order_report.xml',
        'views/kg_pos_filter.xml',
        'views/kg_pos_restaurant_bill_report.xml',
        'views/kg_pos_order_layout.xml',
        'views/meal_time.xml',
        'views/res_users.xml',
        'views/hr_employee.xml',
        'views/templates.xml',
        'views/pos_templates.xml',
        'wizards/wizard_adv_payment_journal.xml',
        'wizards/wizard_export_pajak_online_view.xml',
        'views/kg_pos_session_view.xml',
        # 'data/cron_pos_checkout.xml',
        'wizards/wizard_pos_outlet_view.xml',
        'reports/report_pos_outlet.xml',
        'views/account_view.xml',
        'reports/report_pos_saledetails.xml',
        'wizards/wizard_sale_details_view.xml',
        'wizards/wizard_kg_report_outlet_summary.xml',
        'views/kg_pos_helper.xml',
        'wizards/wizard_sale_details_view.xml',
        'wizards/wizard_meal_redeem.xml',
        'views/pos_category.xml',
        'views/kg_voucher.xml',
        'views/keycard_encoder.xml',
        'reports/kg_rpt_action_pos_order_bill.xml',
    ],
    'demo': [

    ],
    'qweb': [
        'static/src/xml/guest_info.xml',
        'static/src/xml/no_ref.xml',
        'static/src/xml/pos.xml',
        'static/src/xml/advance_payment.xml',
        'static/src/xml/charge_room.xml',
        'static/src/xml/security_pin.xml',
        'static/src/xml/selection_search.xml',
        'static/src/xml/choose_waiter.xml',
        'static/src/xml/tax_widget.xml',
        'static/src/xml/my_value.xml',
        'static/src/xml/discount_order_all_lines_templates.xml',
        'static/src/xml/credit_card.xml',
        'static/src/xml/voucher.xml',
        'static/src/xml/product_custom_name_notes.xml',
        'views/account_bank_statement_line.xml',
        'static/src/xml/print_kitchen_order.xml',
    ],
}
