from . import hr_employee
from . import master_location
from . import master_religion
from . import hr_contract
from . import res_company
from . import salary_rules
from . import hr_payslip
from . import hr_kg_tax_notification
from . import tax_configuration
from . import payroll_configuration
from . import hr_holidays
from . import hr_holidays_status
from . import resource_calendar
from . import resource
from . import hr_holidays_public
from . import bank_transfer_request
