from . import account
from . import kg_account_journal, account_tax
from . import account_bank_statement
from . import kg_issuer_type
from . import account_payment
from . import deposit_type
from . import discount_type
from . import res_company
from . import account_move
from . import account_invoice
from . import invoice_collecting
from . import vendor_bill_account_bank
from . import account_invoice_refund
from . import ir_qweb_field_monetary
from . import account_general_ledger
from . import kg_acquirer_transaction
from . import account_budget
from . import account_financial_report
from . import kg_journal_payment_group
from . import account_move_yearly_balance
